storage:
  default_root: "./Downloads"

general:
  os:
    - "linux"
    - "macos"
  arch:
    - "amd64"
    - "arm64"

categories:
  ISO Images:
    path: "./Downloads/ISOs"
    sources:
      - id: "ubuntu-mate"
      - id: "fedora-coreos"
  ZIMs:
    path: "./Downloads/Kiwix"
    sources:
      - id: "kiwix-wikipedia"
      - id: "kiwix-phet"
      - id: "kiwix-openstreetmap"
  Applications:
    path: "./Downloads/Apps"
    sources:
      - id: "balena-etcher"
  Games:
    path: "./Downloads/Games"
    sources:
      - id: "melonds"
      - id: "mgba"
  Media:
    path: "./Downloads/Media"
    sources:
      - id: "vlc"
      - id: "jellyfin-player"