storage:
  default_root: "./Downloads"

general:
  os:
    - "linux"
    - "windows"
  arch:
    - "amd64"
    - "arm64"

categories:
  ZIMs:
    path: "./Downloads/Kiwix"
    sources:
      - id: "kiwix-wikipedia"
  Applications:
    path: "./Downloads/Apps"
    sources:
      - id: "kiwix-desktop"
      - id: "kiwix-macos"