storage:
  default_root: "./Downloads"

general:
  os:
    - "linux"
    - "macos"
  arch:
    - "amd64"
    - "arm64"

categories:
  ISO Images:
    path: "./Downloads/ISOs"
    sources:
      - id: "ubuntu-mate"
      - id: "fedora-coreos"
  ZIMs:
    path: "./Downloads/Kiwix"
    sources:
      - id: "kiwix-wikipedia"
  Applications:
    path: "./Downloads/Apps"
    sources:
      - id: "balena-etcher"